apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pv-data
  labels:
    app: web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web
  labels:
    customer: acg
spec:
  selector:
    matchLabels:
      app: web
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: mjcarleb/pet_blog_writer:1.1
        name: web-ctr
        ports:
        - containerPort: 5000
        volumeMounts:
        - name:  my-persistent-storage
          mountPath: /data
      volumes:
        - name: my-persistent-storage
          persistentVolumeClaim:
            claimName:  my-pv-data